PROJECT := IMU_Test
DEVICES := LPC1768
# GCC4MBED_DIR := ~/UROP/gcc4mbed
GCC4MBED_DIR := ../..
INCDIRS := BNO055 ../mbed ~/UROP/gcc4mbed/mri
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
