// Generated by gencpp from file fish_msgs/joystick_in.msg
// DO NOT EDIT!


#ifndef FISH_MSGS_MESSAGE_JOYSTICK_IN_H
#define FISH_MSGS_MESSAGE_JOYSTICK_IN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fish_msgs
{
template <class ContainerAllocator>
struct joystick_in_
{
  typedef joystick_in_<ContainerAllocator> Type;

  joystick_in_()
    {
    }
  joystick_in_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::fish_msgs::joystick_in_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fish_msgs::joystick_in_<ContainerAllocator> const> ConstPtr;

}; // struct joystick_in_

typedef ::fish_msgs::joystick_in_<std::allocator<void> > joystick_in;

typedef boost::shared_ptr< ::fish_msgs::joystick_in > joystick_inPtr;
typedef boost::shared_ptr< ::fish_msgs::joystick_in const> joystick_inConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fish_msgs::joystick_in_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fish_msgs::joystick_in_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fish_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'fish_msgs': ['/home/cyndiac/softroboticfish6/catkin_ws/src/fish_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::joystick_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::joystick_in_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::joystick_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::joystick_in_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::joystick_in_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::joystick_in_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fish_msgs::joystick_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fish_msgs::joystick_in_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fish_msgs::joystick_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fish_msgs/joystick_in";
  }

  static const char* value(const ::fish_msgs::joystick_in_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fish_msgs::joystick_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::fish_msgs::joystick_in_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fish_msgs::joystick_in_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct joystick_in_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fish_msgs::joystick_in_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fish_msgs::joystick_in_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FISH_MSGS_MESSAGE_JOYSTICK_IN_H
