(cl:defpackage fish_msgs-msg
  (:use )
  (:export
   "<DEPTHTESTMSG>"
   "DEPTHTESTMSG"
   "<FISHCTRLMSG>"
   "FISHCTRLMSG"
   "<MBEDDATAMSG>"
   "MBEDDATAMSG"
   "<PUMPTESTMSG>"
   "PUMPTESTMSG"
   "<JOYSTICK_IN>"
   "JOYSTICK_IN"
   "<MBEDPUMPSTATUSMSG>"
   "MBEDPUMPSTATUSMSG"
   "<MBEDSTATUSMSG>"
   "MBEDSTATUSMSG"
  ))

