// Generated by gencpp from file fish_msgs/mbedPumpStatusMsg.msg
// DO NOT EDIT!


#ifndef FISH_MSGS_MESSAGE_MBEDPUMPSTATUSMSG_H
#define FISH_MSGS_MESSAGE_MBEDPUMPSTATUSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fish_msgs
{
template <class ContainerAllocator>
struct mbedPumpStatusMsg_
{
  typedef mbedPumpStatusMsg_<ContainerAllocator> Type;

  mbedPumpStatusMsg_()
    : mode(0)
    , yaw(0.0)
    , freq(0.0)  {
    }
  mbedPumpStatusMsg_(const ContainerAllocator& _alloc)
    : mode(0)
    , yaw(0.0)
    , freq(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _freq_type;
  _freq_type freq;




  typedef boost::shared_ptr< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> const> ConstPtr;

}; // struct mbedPumpStatusMsg_

typedef ::fish_msgs::mbedPumpStatusMsg_<std::allocator<void> > mbedPumpStatusMsg;

typedef boost::shared_ptr< ::fish_msgs::mbedPumpStatusMsg > mbedPumpStatusMsgPtr;
typedef boost::shared_ptr< ::fish_msgs::mbedPumpStatusMsg const> mbedPumpStatusMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fish_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fish_msgs': ['/home/fish/softroboticfish6/fish/pi/ros/catkin_ws/src/fish_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d362e13e6bb848f15ea16da4058b765d";
  }

  static const char* value(const ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd362e13e6bb848f1ULL;
  static const uint64_t static_value2 = 0x5ea16da4058b765dULL;
};

template<class ContainerAllocator>
struct DataType< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fish_msgs/mbedPumpStatusMsg";
  }

  static const char* value(const ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n\
float32 yaw\n\
float32 freq\n\
";
  }

  static const char* value(const ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.yaw);
      stream.next(m.freq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mbedPumpStatusMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fish_msgs::mbedPumpStatusMsg_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "freq: ";
    Printer<float>::stream(s, indent + "  ", v.freq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISH_MSGS_MESSAGE_MBEDPUMPSTATUSMSG_H
