// Generated by gencpp from file fish_msgs/mbedStatusMsg.msg
// DO NOT EDIT!


#ifndef FISH_MSGS_MESSAGE_MBEDSTATUSMSG_H
#define FISH_MSGS_MESSAGE_MBEDSTATUSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fish_msgs
{
template <class ContainerAllocator>
struct mbedStatusMsg_
{
  typedef mbedStatusMsg_<ContainerAllocator> Type;

  mbedStatusMsg_()
    : mode(0)
    , value(0.0)  {
    }
  mbedStatusMsg_(const ContainerAllocator& _alloc)
    : mode(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef float _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> const> ConstPtr;

}; // struct mbedStatusMsg_

typedef ::fish_msgs::mbedStatusMsg_<std::allocator<void> > mbedStatusMsg;

typedef boost::shared_ptr< ::fish_msgs::mbedStatusMsg > mbedStatusMsgPtr;
typedef boost::shared_ptr< ::fish_msgs::mbedStatusMsg const> mbedStatusMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fish_msgs::mbedStatusMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fish_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fish_msgs': ['/home/fish/softroboticfish6/fish/pi/ros/catkin_ws/src/fish_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "392256b70b5280d59063ab9c2ddc1efa";
  }

  static const char* value(const ::fish_msgs::mbedStatusMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x392256b70b5280d5ULL;
  static const uint64_t static_value2 = 0x9063ab9c2ddc1efaULL;
};

template<class ContainerAllocator>
struct DataType< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fish_msgs/mbedStatusMsg";
  }

  static const char* value(const ::fish_msgs::mbedStatusMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n\
float32 value\n\
";
  }

  static const char* value(const ::fish_msgs::mbedStatusMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mbedStatusMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fish_msgs::mbedStatusMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fish_msgs::mbedStatusMsg_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISH_MSGS_MESSAGE_MBEDSTATUSMSG_H
