LIBS_DIR		:= ../mbed_libs
PROJECT         := rosserial_test
DEVICES         := LPC1768
GCC4MBED_DIR    := $(GCC4MBED_DIR)
USER_LIBS       := $(LIBS_DIR)/ros_lib $(LIBS_DIR)/MODSERIAL
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
